--- 
after_build: 
  - "set PATH=\"C:\\Program Files (x86)\\Inno Setup 6\";%PATH%"
  - "cd C:\\projects\\virustotaluploader\\"
  - "ISCC.exe inno_setup.iss"
artifacts: 
  - 
    name: release_anycpu
    path: uploader/uploader/build/rel
  - 
    name: setup_anycpu
    path: output
before_build: 
  - "cd uploader"
  - "nuget restore"
configuration: 
  - Release
environment: 
  APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2019"
platform: 
  - "Any CPU"